name: Build App

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on : ubuntu-latest

        steps:
            - uses: actions/checkout@v2
  
            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                    dotnet-version: '9.0.x'
                    include-prerelease: true

            - name: Build with dotnet
              run: dotnet build ./DEX-reports.sln --configuration Release
